# -*- coding: utf-8 -*-
"""practico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unTaTRKrhkgdSrZR-t0LhGL7Ly96QG4F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
estaturas = np.random.uniform(1.5, 2.0, size=100)
pesos = []

for estatatura in estaturas:
    p_min = 18.5 * (estatatura ** 2)
    p_max = 24.9 * (estatatura ** 2)
    peso = np.random.uniform(p_min, p_max)
    pesos.append(peso)

df = pd.DataFrame({'Estatura': estaturas, 'Peso': pesos})

mediax = estaturas.mean()
mediay = np.mean(pesos)
num=0
den=0
for i in range(len(pesos)):
  num=num+((estaturas[i]-mediax)*(pesos[i]-mediay))
  den=den+((estaturas[i]-mediax)**2)

m=num/den
b=mediay-(m*mediax)

y = m * estaturas + b
plt.xlabel('Estatura')
plt.ylabel('Peso')
plt.title('Regresion Lineal')
plt.scatter(df.Estatura, df.Peso, color = 'blue',marker='+')
plt.plot(estaturas, y, color = 'red')
plt.show()